#!/bin/bash

# TulioCP Control Panel upgrade script for target version 1.3.3

#######################################################################################
#######                      Place additional commands below.                   #######
#######################################################################################

# Check if keys folder exists and adjust permissions
if [ -d "$TULIO/data/keys" ]; then
	echo '[ * ] Update permissions'
	chmod 750 "$TULIO/data/keys"
	chown admin:root "$TULIO/data/keys"
fi

mkdir -p /etc/tuliocp
if [[ ! -e /etc/tuliocp/tulio.conf ]]; then
	echo '[ * ] Create global TulioCP config'

	cat << EOF > /etc/tuliocp/tulio.conf
# Do not edit this file, will get overwritten on next upgrade, use /etc/tuliocp/local.conf instead

export TULIO='$TULIO'

[[ -f /etc/tuliocp/local.conf ]] && source /etc/tuliocp/local.conf
EOF
else
	if grep -q '^export TULIO=' /etc/tuliocp/tulio.conf; then
		sed -i "/^export TULIO=/d" /etc/tuliocp/tulio.conf
	fi
	if ! grep -q '^export TULIO=' /etc/tuliocp/tulio.conf; then
		echo "export TULIO='$TULIO'" >> /etc/tuliocp/tulio.conf
	fi
	if ! grep -q 'source /etc/tuliocp/local.conf' /etc/tuliocp/tulio.conf; then
		echo "[[ -f /etc/tuliocp/local.conf ]] && source /etc/tuliocp/local.conf" >> /etc/tuliocp/tulio.conf
	fi
fi
