#!/bin/bash

# TulioCP Control Panel upgrade script for target version 1.3.3

#######################################################################################
#######                      Place additional commands below.                   #######
#######################################################################################

# Check if keys folder exists and adjust permissions
if [ -d "$TULIO/data/keys" ]; then
	echo '[ * ] Update permissions'
	chmod 750 "$TULIO/data/keys"
	chown admin:root "$TULIO/data/keys"
fi

if [[ ! -e /etc/tuliocp/tulio.conf ]]; then
	echo '[ * ] Create global TulioCP config'

	mkdir -p /etc/tuliocp
	echo -e "# Do not edit this file, will get overwritten on next upgrade, use /etc/tuliocp/local.conf instead\n\nexport HESTIA='/usr/local/tulio'\n\n[[ -f /etc/tuliocp/local.conf ]] && source /etc/tuliocp/local.conf" > /etc/tuliocp/tulio.conf
fi
